import os
import json
import zipfile
import pandas as pd
from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
from pathlib import Path
import uuid

app = Flask(__name__)
CORS(app)

UPLOAD_FOLDER = "uploads"
if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)

app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

@app.route('/generate', methods=['POST'])
def generate_metadata():
    try:
        # 1. Terima file: CSV + ZIP gambar
        if 'csv' not in request.files or 'images' not in request.files:
            return jsonify({"error": "CSV dan ZIP gambar harus diupload"}), 400
        
        csv_file = request.files['csv']
        zip_images = request.files['images']
        
        # 2. Buat session ID unik
        session_id = str(uuid.uuid4())
        session_folder = os.path.join(UPLOAD_FOLDER, session_id)
        images_folder = os.path.join(session_folder, "images")
        output_folder = os.path.join(session_folder, "output")
        
        Path(images_folder).mkdir(parents=True, exist_ok=True)
        Path(output_folder).mkdir(parents=True, exist_ok=True)
        
        # 3. Simpan CSV
        csv_path = os.path.join(session_folder, "data.csv")
        csv_file.save(csv_path)
        
        # 4. Ekstrak ZIP gambar
        zip_path = os.path.join(session_folder, "images.zip")
        zip_images.save(zip_path)
        
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(images_folder)
        
        # 5. Baca CSV
        df = pd.read_csv(csv_path)
        
        # 6. Generate metadata untuk setiap baris
        base_image_uri = request.form.get('base_image_uri', 'ipfs://QmPlaceholder/')
        name_prefix = request.form.get('name_prefix', 'NFT Collection')
        description = request.form.get('description', 'Generated by Dashboard')
        
        for _, row in df.iterrows():
            token_id = str(row['token_id'])
            
            # Cari file gambar (bisa .png, .jpg, .jpeg)
            image_filename = None
            for ext in ['.png', '.jpg', '.jpeg']:
                candidate = os.path.join(images_folder, f"{token_id}{ext}")
                if os.path.exists(candidate):
                    image_filename = f"{token_id}{ext}"
                    break
            
            if not image_filename:
                print(f"Warning: Gambar untuk token_id {token_id} tidak ditemukan")
                continue
            
            # Bangun atribut dari CSV (semua kolom kecuali token_id)
            attributes = []
            for col in df.columns:
                if col != 'token_id':
                    attributes.append({
                        "trait_type": col,
                        "value": str(row[col])
                    })
            
            metadata = {
                "name": f"{name_prefix} #{token_id}",
                "description": description,
                "image": base_image_uri + image_filename,
                "attributes": attributes
            }
            
            # Simpan JSON
            json_path = os.path.join(output_folder, f"{token_id}.json")
            with open(json_path, 'w') as f:
                json.dump(metadata, f, indent=2)
        
        # 7. Kompres semua JSON jadi ZIP
        zip_output_path = os.path.join(session_folder, "metadata_results.zip")
        with zipfile.ZipFile(zip_output_path, 'w') as zipf:
            for json_file in Path(output_folder).glob("*.json"):
                zipf.write(json_file, json_file.name)
        
        # 8. Kirim ZIP ke user
        return send_file(zip_output_path, as_attachment=True, download_name="metadata_results.zip")
    
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/health', methods=['GET'])
def health():
    return jsonify({"status": "ok"})

if __name__ == '__main__':
    app.run(debug=True, port=5000)