import os
import json
import zipfile
import pandas as pd
from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
from pathlib import Path
import uuid
import traceback

app = Flask(__name__)
CORS(app)

UPLOAD_FOLDER = "uploads"
if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)

app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

# Helper: baca JSON metadata
def parse_json_metadata(json_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    rows = []
    for idx, item in enumerate(data):
        token_id = item.get('token_id') or item.get('id') or str(idx + 1)
        attributes = item.get('attributes', {})
        
        # Jika attributes dalam bentuk list (seperti OpenSea)
        if isinstance(attributes, list):
            attr_dict = {}
            for attr in attributes:
                attr_dict[attr['trait_type']] = attr['value']
            attributes = attr_dict
        
        row = {'token_id': token_id}
        row.update(attributes)
        rows.append(row)
    
    return pd.DataFrame(rows)

@app.route('/generate', methods=['POST'])
def generate_metadata():
    temp_session = None
    try:
        # 1. Terima file
        if 'images' not in request.files:
            return jsonify({"error": "ZIP images required"}), 400
        
        zip_images = request.files['images']
        
        if zip_images.filename == '':
            return jsonify({"error": "Empty file"}), 400
        
        # 2. Buat session folder
        session_id = str(uuid.uuid4())
        session_folder = os.path.join(UPLOAD_FOLDER, session_id)
        images_folder = os.path.join(session_folder, "images")
        output_folder = os.path.join(session_folder, "output")
        
        os.makedirs(images_folder, exist_ok=True)
        os.makedirs(output_folder, exist_ok=True)
        
        # 3. Simpan & ekstrak ZIP gambar
        zip_path = os.path.join(session_folder, "images.zip")
        zip_images.save(zip_path)
        
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(images_folder)
        
        # 4. Baca data (CSV atau JSON)
        df = None
        if 'csv' in request.files and request.files['csv'].filename != '':
            csv_file = request.files['csv']
            csv_path = os.path.join(session_folder, "data.csv")
            csv_file.save(csv_path)
            df = pd.read_csv(csv_path)
        elif 'json' in request.files and request.files['json'].filename != '':
            json_file = request.files['json']
            json_path = os.path.join(session_folder, "data.json")
            json_file.save(json_path)
            df = parse_json_metadata(json_path)
        else:
            return jsonify({"error": "CSV or JSON file required"}), 400
        
        # 5. Normalisasi kolom token_id (support 'id' atau 'token_id')
        if 'token_id' not in df.columns:
            if 'id' in df.columns:
                df.rename(columns={'id': 'token_id'}, inplace=True)
            else:
                return jsonify({"error": "CSV/JSON must have 'token_id' or 'id' column"}), 400
        
        # 6. Parameter
        base_image_uri = request.form.get('base_image_uri', 'ipfs://QmPlaceholder/')
        name_prefix = request.form.get('name_prefix', 'NFT Collection')
        description = request.form.get('description', 'Generated by Dashboard')
        
        # 7. Cari file gambar
        existing_images = {}
        for ext in ['*.png', '*.jpg', '*.jpeg', '*.PNG', '*.JPG', '*.JPEG']:
            for img_path in Path(images_folder).glob(ext):
                token_id = img_path.stem
                existing_images[token_id] = img_path.name
        
        # 8. Generate metadata
        generated_count = 0
        for _, row in df.iterrows():
            token_id = str(row['token_id'])
            
            if token_id not in existing_images:
                print(f"Warning: Gambar untuk token {token_id} tidak ditemukan")
                continue
            
            attributes = []
            for col in df.columns:
                if col != 'token_id':
                    attributes.append({
                        "trait_type": col,
                        "value": str(row[col])
                    })
            
            metadata = {
                "name": f"{name_prefix} #{token_id}",
                "description": description,
                "image": base_image_uri + existing_images[token_id],
                "attributes": attributes
            }
            
            json_path = os.path.join(output_folder, f"{token_id}.json")
            with open(json_path, 'w') as f:
                json.dump(metadata, f, indent=2)
            
            generated_count += 1
        
        if generated_count == 0:
            return jsonify({"error": "No matching images found"}), 400
        
        # 9. Buat ZIP hasil
        zip_output_path = os.path.join(session_folder, "metadata_results.zip")
        with zipfile.ZipFile(zip_output_path, 'w') as zipf:
            for json_file in Path(output_folder).glob("*.json"):
                zipf.write(json_file, json_file.name)
        
        return send_file(
            zip_output_path, 
            as_attachment=True, 
            download_name="metadata_results.zip",
            mimetype='application/zip'
        )
        
    except Exception as e:
        print("="*50)
        print("ERROR DETAILS:")
        print(traceback.format_exc())
        print("="*50)
        return jsonify({"error": str(e)}), 500

@app.route('/health', methods=['GET'])
def health():
    return jsonify({"status": "ok"})

if __name__ == '__main__':
    app.run(debug=True, port=5000)