import { useState } from 'react'

function App() {
  const [csvFile, setCsvFile] = useState(null)
  const [jsonFile, setJsonFile] = useState(null)
  const [zipFile, setZipFile] = useState(null)
  const [fileType, setFileType] = useState('csv')
  const [namePrefix, setNamePrefix] = useState('My NFT')
  const [description, setDescription] = useState('Generated by Dashboard')
  const [loading, setLoading] = useState(false)

  const downloadTemplate = () => {
    const template = `token_id,warna,topi,langka
1,Merah,Topi Jerami,Common
2,Biru,Topi Koboi,Rare
3,Hijau,Topi Baseball,Epic`
    
    const blob = new Blob([template], { type: 'text/csv' })
    const url = window.URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'template_nft_collection.csv'
    a.click()
    window.URL.revokeObjectURL(url)
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    
    if (fileType === 'csv' && !csvFile) {
      alert('Upload CSV file dulu!')
      return
    }
    if (fileType === 'json' && !jsonFile) {
      alert('Upload JSON file dulu!')
      return
    }
    if (!zipFile) {
      alert('Upload ZIP gambar dulu!')
      return
    }

    setLoading(true)
    const formData = new FormData()
    
    if (fileType === 'csv') {
      formData.append('csv', csvFile)
    } else {
      formData.append('json', jsonFile)
    }
    
    formData.append('images', zipFile)
    formData.append('name_prefix', namePrefix)
    formData.append('description', description)
    formData.append('base_image_uri', 'ipfs://QmYourCID/')

    try {
      const response = await fetch('http://localhost:5000/generate', {
        method: 'POST',
        body: formData
      })
      
      if (response.ok) {
        const blob = await response.blob()
        const url = window.URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = 'metadata_results.zip'
        a.click()
        window.URL.revokeObjectURL(url)
        alert('✅ Berhasil! ZIP hasil metadata siap download.')
      } else {
        const error = await response.json()
        alert('❌ Gagal: ' + (error.error || 'Unknown error'))
      }
    } catch (error) {
      console.error(error)
      alert('❌ Error: ' + error.message)
    } finally {
      setLoading(false)
    }
  }

  const styles = {
    container: {
      minHeight: '100vh',
      backgroundColor: '#0f172a',
      color: 'white',
      padding: '2rem',
      fontFamily: 'system-ui, -apple-system, sans-serif'
    },
    card: {
      maxWidth: '700px',
      margin: '0 auto',
      backgroundColor: '#1e293b',
      borderRadius: '1rem',
      padding: '2rem',
      boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)'
    },
    title: {
      fontSize: '1.875rem',
      fontWeight: 'bold',
      marginBottom: '0.5rem',
      textAlign: 'center',
      background: 'linear-gradient(135deg, #60a5fa, #a78bfa)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent'
    },
    subtitle: {
      textAlign: 'center',
      color: '#94a3b8',
      marginBottom: '2rem',
      fontSize: '0.875rem'
    },
    form: {
      display: 'flex',
      flexDirection: 'column',
      gap: '1.25rem'
    },
    label: {
      display: 'block',
      marginBottom: '0.5rem',
      fontWeight: '500',
      color: '#cbd5e1'
    },
    input: {
      width: '100%',
      padding: '0.625rem',
      backgroundColor: '#0f172a',
      border: '1px solid #334155',
      borderRadius: '0.5rem',
      color: 'white',
      fontSize: '0.875rem'
    },
    textarea: {
      width: '100%',
      padding: '0.625rem',
      backgroundColor: '#0f172a',
      border: '1px solid #334155',
      borderRadius: '0.5rem',
      color: 'white',
      fontSize: '0.875rem',
      fontFamily: 'inherit'
    },
    button: {
      width: '100%',
      padding: '0.75rem',
      backgroundColor: loading ? '#475569' : '#3b82f6',
      border: 'none',
      borderRadius: '0.5rem',
      color: 'white',
      fontWeight: 'bold',
      fontSize: '1rem',
      cursor: loading ? 'not-allowed' : 'pointer',
      marginTop: '0.5rem',
      transition: 'background-color 0.2s'
    },
    buttonSecondary: {
      width: '100%',
      padding: '0.75rem',
      backgroundColor: '#10b981',
      border: 'none',
      borderRadius: '0.5rem',
      color: 'white',
      fontWeight: 'bold',
      fontSize: '1rem',
      cursor: 'pointer',
      marginTop: '0.5rem',
      transition: 'background-color 0.2s'
    },
    radioGroup: {
      display: 'flex',
      gap: '1rem',
      alignItems: 'center',
      marginBottom: '1rem'
    },
    radioLabel: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
      cursor: 'pointer'
    },
    fileInfo: {
      fontSize: '0.75rem',
      color: '#64748b',
      marginTop: '0.25rem'
    }
  }

  return (
    <div style={styles.container}>
      <div style={styles.card}>
        <h1 style={styles.title}>
          🚀 NFT Metadata Generator
        </h1>
        <div style={styles.subtitle}>
          Universal CSV & JSON support + Download Template
        </div>
        
        <form onSubmit={handleSubmit} style={styles.form}>
          {/* Pilih tipe file */}
          <div>
            <label style={styles.label}>📁 Tipe File Data</label>
            <div style={styles.radioGroup}>
              <label style={styles.radioLabel}>
                <input
                  type="radio"
                  value="csv"
                  checked={fileType === 'csv'}
                  onChange={() => setFileType('csv')}
                />
                CSV (.csv)
              </label>
              <label style={styles.radioLabel}>
                <input
                  type="radio"
                  value="json"
                  checked={fileType === 'json'}
                  onChange={() => setFileType('json')}
                />
                JSON (.json)
              </label>
            </div>
          </div>

          {/* Tombol Download Template */}
          <div>
            <button
              type="button"
              onClick={downloadTemplate}
              style={styles.buttonSecondary}
              onMouseEnter={(e) => e.currentTarget.style.backgroundColor = '#059669'}
              onMouseLeave={(e) => e.currentTarget.style.backgroundColor = '#10b981'}
            >
              📥 Download Template CSV
            </button>
            <div style={styles.fileInfo}>
              Download template, isi data kamu, lalu upload kembali
            </div>
          </div>

          {/* Upload file sesuai tipe */}
          {fileType === 'csv' && (
            <div>
              <label style={styles.label}>📄 File CSV</label>
              <input
                type="file"
                accept=".csv"
                onChange={(e) => setCsvFile(e.target.files[0])}
                style={styles.input}
              />
              <div style={styles.fileInfo}>
                Kolom wajib: token_id (atau id) + atribut bebas
              </div>
            </div>
          )}

          {fileType === 'json' && (
            <div>
              <label style={styles.label}>📄 File JSON</label>
              <input
                type="file"
                accept=".json"
                onChange={(e) => setJsonFile(e.target.files[0])}
                style={styles.input}
              />
              <div style={styles.fileInfo}>
                Format: array of objects dengan token_id/id + attributes
              </div>
            </div>
          )}

          {/* ZIP Gambar */}
          <div>
            <label style={styles.label}>🖼️ ZIP Gambar</label>
            <input
              type="file"
              accept=".zip"
              onChange={(e) => setZipFile(e.target.files[0])}
              style={styles.input}
            />
            <div style={styles.fileInfo}>
              Nama file gambar harus sesuai token_id (contoh: 1.png, 2.png)
            </div>
          </div>

          {/* Nama Koleksi */}
          <div>
            <label style={styles.label}>🏷️ Nama Koleksi</label>
            <input
              type="text"
              value={namePrefix}
              onChange={(e) => setNamePrefix(e.target.value)}
              style={styles.input}
              placeholder="Contoh: CryptoAnimals"
            />
          </div>

          {/* Deskripsi */}
          <div>
            <label style={styles.label}>📝 Deskripsi</label>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              style={styles.textarea}
              rows="3"
              placeholder="Deskripsi koleksi NFT Anda..."
            />
          </div>

          {/* Tombol Generate */}
          <button
            type="submit"
            disabled={loading}
            style={styles.button}
            onMouseEnter={(e) => {
              if (!loading) e.currentTarget.style.backgroundColor = '#2563eb'
            }}
            onMouseLeave={(e) => {
              if (!loading) e.currentTarget.style.backgroundColor = '#3b82f6'
            }}
          >
            {loading ? '⚙️ Memproses...' : '✨ Generate Metadata'}
          </button>
        </form>
      </div>
    </div>
  )
}

export default App